#!/usr/bin/env python3
"""
amber_pipeline.py  —  Phase 3: post-Gaussian AMBER parameterization
Runs espgen → resp → antechamber → prepgen → parmchk2 (GAFF + ff14SB).

Expects resp.in, resp.qin, and <resname>.mc to be present in the working
directory (generated by run.py in Phase 1).

Usage:
    python amber_pipeline.py MEO_hf.log
    python amber_pipeline.py MEO_hf.log --resname MEO --charge 0
    python amber_pipeline.py MEO_hf.log --workdir /path/to/workdir
"""

import sys
import argparse
import yaml
from pathlib import Path
from parameterize import run_amber_pipeline, get_resname


def load_config(path='config.yaml'):
    try:
        with open(path) as f:
            return yaml.safe_load(f)
    except FileNotFoundError:
        return {}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Run AMBER parameterization pipeline from Gaussian HF log"
    )
    parser.add_argument('log',              help='Gaussian HF/ESP log (e.g. MEO_hf.log)')
    parser.add_argument('--resname',        default=None,
                        help='Residue name (default: derived from log filename or config.yaml)')
    parser.add_argument('-c', '--charge',   type=int, default=None,
                        help='Net molecular charge (default: from config.yaml or 0)')
    parser.add_argument('--workdir',        default='.',
                        help='Working directory (default: current directory)')
    args = parser.parse_args()

    cfg      = load_config()
    res_cfg  = cfg.get('residue', {})
    amb_cfg  = cfg.get('amber', {}) or {}

    charge  = args.charge  if args.charge  is not None else res_cfg.get('charge', 0)
    workdir = args.workdir if args.workdir != '.' else (amb_cfg.get('workdir') or '.')

    if args.resname:
        resname = args.resname
    elif res_cfg.get('input_pdb'):
        resname = get_resname(res_cfg['input_pdb'])
    else:
        resname = Path(args.log).stem.replace('_hf', '').replace('_opt', '')

    mc_file = Path(workdir) / f"{resname}.mc"
    if not mc_file.exists():
        sys.exit(f"Error: {mc_file} not found — run 'python run.py' first to generate it.")

    print(f"Residue : {resname}  (charge {charge:+d})")
    print(f"Log     : {args.log}")
    print(f"MC file : {mc_file}")
    print()

    run_amber_pipeline(
        hf_log      = args.log,
        resname     = resname,
        charge      = charge,
        mc_file     = str(mc_file),
        workdir     = workdir,
        atom_type   = amb_cfg.get('atom_type', 'amber'),
        ff14sb      = amb_cfg.get('ff14sb_frcmod', True),
    )
