#!/usr/bin/env python3
"""
amber_pipeline.py  --  Phase 3: post-Gaussian AMBER parameterization
Runs espgen -> resp -> antechamber -> prepgen -> parmchk2 (GAFF + ff14SB).

Expects resp.in, resp.qin, and <base>.mc to be present in the working
directory (generated by run.py in Phase 1).

The working directory is derived from the HF log path (its parent), which
is the variant subdirectory written by run.py:
  <resname>/middle/   for position=middle
  <resname>/cterm/    for position=cterm
  <resname>/nterm/    for position=nterm

Usage:
    python amber_pipeline.py KME3/middle/KME3_hf.log
    python amber_pipeline.py KME3/cterm/KME3_cterm_hf.log
    python amber_pipeline.py KME3/nterm/KME3_nterm_hf.log --charge 1
"""

import sys
import argparse
import yaml
from pathlib import Path
from craft import run_amber_pipeline, get_resname


def load_config(path='config.yaml'):
    try:
        with open(path) as f:
            return yaml.safe_load(f)
    except FileNotFoundError:
        return {}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Run AMBER parameterization pipeline from Gaussian HF log"
    )
    parser.add_argument('log',              help='Gaussian HF/ESP log (e.g. KME3_hf.log)')
    parser.add_argument('--resname',        default=None,
                        help='Residue name (default: derived from config.yaml or log filename)')
    parser.add_argument('-c', '--charge',   type=int, default=None,
                        help='Net molecular charge (default: from config.yaml or 0)')
    parser.add_argument('--workdir',        default='.',
                        help='Working directory (default: parent of the log file)')
    args = parser.parse_args()

    cfg      = load_config()
    res_cfg  = cfg.get('residue', {})
    amb_cfg  = cfg.get('amber', {}) or {}
    cap_cfg  = cfg.get('cap',   {}) or {}

    charge   = args.charge if args.charge is not None else res_cfg.get('charge', 0)
    position = res_cfg.get('position', 'middle')
    suffix   = '' if position == 'middle' else f'_{position}'

    workdir = (args.workdir if args.workdir != '.'
               else (amb_cfg.get('workdir') or str(Path(args.log).resolve().parent)))

    capped_pdb = cap_cfg.get('output_pdb') or None   # None -> auto-detect

    if args.resname:
        resname = args.resname
    elif res_cfg.get('input_pdb'):
        resname = get_resname(res_cfg['input_pdb'])
    else:
        stem = Path(args.log).stem
        for tag in ('_hf', '_opt', '_cterm', '_nterm'):
            stem = stem.replace(tag, '')
        resname = stem

    mc_file = Path(workdir) / f"{resname}{suffix}.mc"
    if not mc_file.exists():
        sys.exit(f"Error: {mc_file} not found -- run 'python run.py' first to generate it.")

    print(f"Residue  : {resname}  (charge {charge:+d})")
    print(f"Position : {position}")
    print(f"Log      : {args.log}")
    print(f"MC file  : {mc_file}")
    print()

    run_amber_pipeline(
        hf_log      = args.log,
        resname     = resname,
        charge      = charge,
        mc_file     = str(mc_file),
        workdir     = workdir,
        atom_type   = amb_cfg.get('atom_type', 'amber'),
        ff14sb      = amb_cfg.get('ff14sb_frcmod', True),
        capped_pdb  = capped_pdb,
        position    = position,
    )
